# Copyright (c) 2023, MASSACHUSETTS INSTITUTE OF TECHNOLOGY
# Subject to FAR 52.227-11 - Patent Rights - Ownership by the Contractor (May 2014).
model:
  _target_: src.charge3net.models.e3.E3DensityModel
  num_interactions: 3
  num_neighbors: 20
  mul: 500
  lmax: 4
  cutoff: 4.0
  basis: "gaussian"
  num_basis: 20

optimizer:
  _target_: torch.optim.Adam
  _partial_: true

lr_scheduler:
  _target_: src.charge3net.models.scheduler.PowerDecayScheduler
  _partial_: true
  alpha: 0.96

criterion:
  _target_: torch.nn.L1Loss

batch_size: ${batch_size}
max_predict_batch_probes: 2500
